import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/utils/trpc";
// import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink, NavigationMenuTrigger } from "~/components/ui/navigation-menu"; // Import Navigation components
import { Nav } from "~/components/navbar";
import { DynamicProvider } from "~/components/dynamic-provider";
import { SafeAccountProvider } from "~/components/safe-account-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${inter.variable}`}>
        <div className="m-auto max-w-5xl">
          <TRPCReactProvider>
            <DynamicProvider>
              <Nav />
              <hr className="mt-4" />
              <SafeAccountProvider>{children}</SafeAccountProvider>
            </DynamicProvider>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
